---
- name: Log in using service account
  command: "oc login {{ ocp_uri }} --token={{ ocp_token }}"

- name: Configuring Admin users
  command: "oc adm policy add-role-to-group admin {{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }}-admins -n {{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }} --token={{ ocp_token }}"
  with_items: "{{ projects }}"

- name: Assign Admin user to OCP role
  vars:
    namespace: "{{ tenant_name|lower|replace('_', '-') }}-{{ item.0.name|lower|replace('_', '-') }}"
    user: "{{ item.1 }} "
  command: "oc adm policy add-role-to-user admin {{ user }} -n {{ namespace }} --token={{ ocp_token }}"
  with_subelements:
    - "{{ projects }}"
    - admins
    - skip_missing: yes

- name: Configuring Standard users
  command: "oc adm policy add-role-to-group view {{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }}-users -n {{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }} --token={{ ocp_token }}"
  with_items: "{{ projects }}"

- name: Assign basic user to OCP role
  vars:
    namespace: "{{ tenant_name|lower|replace('_', '-') }}-{{ item.0.name|lower|replace('_', '-') }}"
    user: "{{ item.1 }} "
  command: "oc adm policy add-role-to-user view {{ user }} -n {{ namespace }} --token={{ ocp_token }}"
  with_subelements:
    - "{{ projects }}"
    - users
    - skip_missing: yes  

- name: Logout of service account
  command: "oc logout"


