---
- name: Creating OCP projects
  oc:
    state: present
    inline:
      kind: ProjectRequest
      metadata:
        name: "{{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }}"
      displayName: "{{ item.displayName | default(omit) }}"
      description: "{{ item.description | default(omit) }}"
    token: "{{ ocp_token }}"
    validate_certs: no
  with_items: "{{ projects }}"

- include_tasks: "create_role_bindings.yml"
...