---
- name: Deleting OCP project(s)
  oc:
    state: absent
    inline:
      kind: ProjectRequest
      metadata:
        name: "{{ tenant_name | lower | replace('_', '-') }}-{{ item.name | lower | replace('_', '-') }}"
    token: "{{ ocp_token }}"
    validate_certs: no
  with_items: "{{ projects }}"
...