---
- name: Deleting OCP project(s)
  openshift_raw:
    state: absent
    definition: "{{ lookup('template', 'project.yml') | from_yaml }}"
    token: "{{ ocp_token }}"
    validate_certs: no
  with_items: "{{ projects }}"
...