---
- name: Logging in using service account
  command: "oc login {{ ocp_uri }} --token={{ ocp_token }}"

- name: Un-assigning users from admin OCP role
  vars:
    namespace: "{{ tenant_name|lower|replace('_', '-') }}-{{ item.0.name|lower|replace('_', '-') }}"
    user: "{{ item.1 }} "
  command: "oc adm policy remove-role-from-user admin {{ user }} -n {{ namespace }} --token={{ ocp_token }}"
  with_subelements:
    - "{{ projects }}"
    - admins
    - skip_missing: yes

- name: Un-assigning users from view OCP role
  vars:
    namespace: "{{ tenant_name|lower|replace('_', '-') }}-{{ item.0.name|lower|replace('_', '-') }}"
    user: "{{ item.1 }}"
  command: "oc adm policy remove-role-from-user view {{ user }} -n {{ namespace }} --token={{ ocp_token }}"
  with_subelements:
    - "{{ projects }}"
    - users
    - skip_missing: yes  

- name: Logout of service account
  command: "oc logout"


