---
- name: Removing any pre-existing resource quotas
  openshift_raw:
    state: absent
    definition: "{{ lookup('template', 'quota.yml') | from_yaml }}"
    token: "{{ ocp_token }}"
    validate_certs: no
  with_items: "{{ projects }}"

- name: Re-creating resource quotas
  openshift_raw:
    state: present
    definition: "{{ lookup('template', 'quota.yml') | from_yaml }}"
    token: "{{ ocp_token }}"
    validate_certs: no
  with_items: "{{ projects }}"